package io.fplpicks.application.model

data class PlayerGameweekFeatures(
    val position: Int,
    val isHome: Boolean,
    val opponentStrength: Int,
    val lastOpponentStrength: Int,
    val last3GamesOpponentStrengthAvg: Double,
    val last5GamesOpponentStrengthAvg: Double,
    val last5GamesCleansSheetsAvg: Double,
    val last5GamesGoalsScoredAvg: Double,
    val last5GamesAssistsAvg: Double,
    val last5GamesBonusPointsAvg: Double,
    val lastGamePoints: Int,
    val last2GamesPointsAvg: Double,
    val last3GamesPointsAvg: Double,
    val last5GamesPointsAvg: Double,
    val seasonAvgPointsToDate: Double,
    val seasonPointsStdDev: Double,
    val seasonAvgCleanSheets: Double,
    val seasonAvgGoalsScored: Double,
    val seasonAvgAssists: Double,
    val seasonAvgBonusPointsAvg: Double,
    val seasonAvgMinutesPlayed: Double,
    val points: Double,
 )